apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../template
nameSuffix: -automated-qa
patches:
  - path: patch.yaml
  # Patch the CronJob container name
  - target:
      kind: CronJob
      name: turtles-cronjob
    options:
      allowNameChange: true
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/name
        value: turtles-cronjob-automated-qa
