[tool.poetry]
name = "wastd"
version = "1.0.1"
description = "Western Australian Sea Turtles Database"
authors = ["Florian Mayer <florian.mayer@dbca.wa.gov.au>", "Ashley Felton <ashley.felton@dbca.wa.gov.au>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "3.2.20"
django-extensions = "3.2.1"
psycopg2 = "2.9.5"
dj-database-url = "1.0.0"
gunicorn = "20.1.0"
python-dotenv = "0.21.0"
dbca-utils = "1.1.6"
django-fsm = "2.8.1"
django-fsm-log = "3.1.0"
django-fsm-admin = "1.2.5"
python-dateutil = "2.8.2"
python-slugify = "8.0.1"
django-filter = "22.1"
django-polymorphic = "3.1.0"
django-reversion = "5.0.4"
django-leaflet = "0.28.3"
django-crispy-forms = "1.14.0"
django-bootstrap4 = "22.3"
xmltodict = "0.13.0"
pandas = "1.5.2"
django-tables2 = "2.4.1"
django-select2 = "8.0.0"
django-easy-select2 = "1.5.8"
django-ajax-selects = "2.2.0"
django-geojson = "4.0.0"
django-import-export = "3.1.0"
django-export-download = "0.2.3"
pillow = "9.5.0"
django-grappelli = "3.0.4"
whitenoise = {version = "6.3.0", extras = ["brotli"]}
phonenumbers = "8.13.3"
django-phonenumber-field = "7.0.1"
mssql-django = "1.2"
webtemplate-dbca = "1.5.1"
django-bootstrap-pagination = "1.7.1"

[tool.poetry.group.dev.dependencies]
ipython = "^8.14.0"
ipdb = "^0.13.9"
black = "^22.10.0"
ruff = "^0.0.285"
sphinx = "^7.0.1"
vulture = "^2.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
# Enable Pyflakes `E` and `F` codes.
select = ["E", "F"]
# Never enforce `E501` (line length violations).
ignore = ["E501"]
# Always autofix.
fix = true
exclude = ["__pycache__", "migrations"]
