apiVersion: apps/v1
kind: Deployment
metadata:
  name: turtles-deployment
spec:
  template:
    spec:
      containers:
        - name: turtles
          envFrom:
            - secretRef:
                name: turtles-env-uat
